-- CREATE DATABASE

CREATE TABLE public."Type" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,	
	CONSTRAINT "PK_Type" PRIMARY KEY ("id")
);

CREATE TABLE public."Goal" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,	
	CONSTRAINT "PK_Goal" PRIMARY KEY ("id")
);	

CREATE TABLE public."City" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,	
	CONSTRAINT "PK_City" PRIMARY KEY ("id")
);		

CREATE TABLE public."District" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,	
	CONSTRAINT "PK_District" PRIMARY KEY ("id")
);		

CREATE TABLE public."Property" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"partner_id" varchar(50) NOT NULL,
	"type_id" int4 NOT NULL,
	"district_id" int4 NOT NULL,
	"city_id" int4 NOT NULL,
	"goal_id" int4 NOT NULL,
	"number" varchar(50) NULL,
	"street" varchar(100) NOT NULL,
	"size" int4 NOT NULL,
	"bedroom_number" int4 NOT NULL,
	"room_number" int4 NOT NULL,
	"bath_number" int4 NOT NULL,
	"parking_number" int4 NOT NULL,
	CONSTRAINT "PK_Property" PRIMARY KEY ("id"),
	CONSTRAINT "FK_Property_Type_Id" FOREIGN KEY ("type_id") REFERENCES public."Type"("id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Property_District_Id" FOREIGN KEY ("district_id") REFERENCES public."District"("id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Property_City_Id" FOREIGN KEY ("city_id") REFERENCES public."City"("id") ON DELETE restrict,
	CONSTRAINT "FK_Property_Goal_Id" FOREIGN KEY ("goal_id") REFERENCES public."Goal"("id") ON DELETE RESTRICT
);		

CREATE INDEX "IX_Property_Type_Id" ON public."Property" USING btree ("type_id");
CREATE INDEX "IX_Property_District_Id" ON public."Property" USING btree ("district_id");
CREATE INDEX "IX_Property_City_Id" ON public."Property" USING btree ("city_id");
CREATE INDEX "IX_Property_Goal_Id" ON public."Property" USING btree ("goal_id");	

CREATE TABLE public."Management" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"partner_id" varchar(50) NOT NULL,
	"price" numeric NOT NULL,
	"tax_rate" numeric NULL,
	"property_tax" numeric NULL,
	"created_on" timestamp NULL,
	"is_available" bool NOT NULL DEFAULT false,
	
	CONSTRAINT "PK_Management" PRIMARY KEY ("id")	
);

INSERT INTO public."Goal" ("name") VALUES('Sell');
INSERT INTO public."Goal" ("name") VALUES('Rent');

INSERT INTO public."Type" ("name") VALUES('Apartment');
INSERT INTO public."Type" ("name") VALUES('House');
INSERT INTO public."Type" ("name") VALUES('Condo');

--DELETE 
DELETE FROM "Management";
DELETE FROM "Property";
--DELETE FROM "Type";
--DELETE FROM "Goal";
DELETE FROM "City";
DELETE FROM "District";

--DROP
DROP TABLE "Management";
DROP TABLE "Property";
DROP TABLE "Type";
DROP TABLE "Goal";
DROP TABLE "City";
DROP TABLE "District";